name: GITHUB ACITON Weater
on:
  push:
    branches: [ main ]
  schedule:
    - cron: 0 23 * * *
jobs:
  # 这个jobs中的一个任务，名字叫build(随便怎么取)
  build:
    # 用来指定这个任务在什么操作系统上跑(服务器是GitHub免费提供的)
    runs-on: ubuntu-latest
    steps:
    # 首先copy git仓库到虚拟机上
      - name: Checkout
        uses: actions/checkout@v1
        # 安装初始化python
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
        # 安装脚本所需的依赖
      - name: 'Install requests'
        run: pip install requests
        # 运行脚本
      - name: 'Working'
        env:	#添加环境变量
          SCKEY: ${{ secrets.SCKEY }}
          SKEY: ${{ secrets.SKEY }}
        run: python ./weater.py
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 天气预报 (${{env.REPORT_DATE}})
          body: file://result.html
          to: mehoney99@163.com
          from: GitHub Actions
